/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminiRouteImport } from './routes/termini'
import { Route as SicurezzaRouteImport } from './routes/sicurezza'
import { Route as ServiziRouteImport } from './routes/servizi'
import { Route as RecuperaPasswordRouteImport } from './routes/recupera-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrezziRouteImport } from './routes/prezzi'
import { Route as MessaggiRouteImport } from './routes/messaggi'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CookieRouteImport } from './routes/cookie'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as ConfermaEmailRouteImport } from './routes/conferma-email'
import { Route as ComeFunzionaRouteImport } from './routes/come-funziona'
import { Route as AggiornaPasswordRouteImport } from './routes/aggiorna-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerificaIdentitaIdRouteImport } from './routes/verifica-identita.$id'
import { Route as ProfessionistaProfiloRouteImport } from './routes/professionista.profilo'
import { Route as ProfessionistaDashboardRouteImport } from './routes/professionista.dashboard'
import { Route as FamigliaDashboardRouteImport } from './routes/famiglia.dashboard'
import { Route as ChatConversationIdRouteImport } from './routes/chat.$conversationId'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe-webhook'

const TerminiRoute = TerminiRouteImport.update({
  id: '/termini',
  path: '/termini',
  getParentRoute: () => rootRouteImport,
} as any)
const SicurezzaRoute = SicurezzaRouteImport.update({
  id: '/sicurezza',
  path: '/sicurezza',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiziRoute = ServiziRouteImport.update({
  id: '/servizi',
  path: '/servizi',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperaPasswordRoute = RecuperaPasswordRouteImport.update({
  id: '/recupera-password',
  path: '/recupera-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrezziRoute = PrezziRouteImport.update({
  id: '/prezzi',
  path: '/prezzi',
  getParentRoute: () => rootRouteImport,
} as any)
const MessaggiRoute = MessaggiRouteImport.update({
  id: '/messaggi',
  path: '/messaggi',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieRoute = CookieRouteImport.update({
  id: '/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfermaEmailRoute = ConfermaEmailRouteImport.update({
  id: '/conferma-email',
  path: '/conferma-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ComeFunzionaRoute = ComeFunzionaRouteImport.update({
  id: '/come-funziona',
  path: '/come-funziona',
  getParentRoute: () => rootRouteImport,
} as any)
const AggiornaPasswordRoute = AggiornaPasswordRouteImport.update({
  id: '/aggiorna-password',
  path: '/aggiorna-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificaIdentitaIdRoute = VerificaIdentitaIdRouteImport.update({
  id: '/verifica-identita/$id',
  path: '/verifica-identita/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionistaProfiloRoute = ProfessionistaProfiloRouteImport.update({
  id: '/professionista/profilo',
  path: '/professionista/profilo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionistaDashboardRoute = ProfessionistaDashboardRouteImport.update({
  id: '/professionista/dashboard',
  path: '/professionista/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FamigliaDashboardRoute = FamigliaDashboardRouteImport.update({
  id: '/famiglia/dashboard',
  path: '/famiglia/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatConversationIdRoute = ChatConversationIdRouteImport.update({
  id: '/chat/$conversationId',
  path: '/chat/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aggiorna-password': typeof AggiornaPasswordRoute
  '/come-funziona': typeof ComeFunzionaRoute
  '/conferma-email': typeof ConfermaEmailRoute
  '/contatti': typeof ContattiRoute
  '/cookie': typeof CookieRoute
  '/login': typeof LoginRoute
  '/messaggi': typeof MessaggiRoute
  '/prezzi': typeof PrezziRoute
  '/privacy': typeof PrivacyRoute
  '/recupera-password': typeof RecuperaPasswordRoute
  '/servizi': typeof ServiziRoute
  '/sicurezza': typeof SicurezzaRoute
  '/termini': typeof TerminiRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/famiglia/dashboard': typeof FamigliaDashboardRoute
  '/professionista/dashboard': typeof ProfessionistaDashboardRoute
  '/professionista/profilo': typeof ProfessionistaProfiloRoute
  '/verifica-identita/$id': typeof VerificaIdentitaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aggiorna-password': typeof AggiornaPasswordRoute
  '/come-funziona': typeof ComeFunzionaRoute
  '/conferma-email': typeof ConfermaEmailRoute
  '/contatti': typeof ContattiRoute
  '/cookie': typeof CookieRoute
  '/login': typeof LoginRoute
  '/messaggi': typeof MessaggiRoute
  '/prezzi': typeof PrezziRoute
  '/privacy': typeof PrivacyRoute
  '/recupera-password': typeof RecuperaPasswordRoute
  '/servizi': typeof ServiziRoute
  '/sicurezza': typeof SicurezzaRoute
  '/termini': typeof TerminiRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/famiglia/dashboard': typeof FamigliaDashboardRoute
  '/professionista/dashboard': typeof ProfessionistaDashboardRoute
  '/professionista/profilo': typeof ProfessionistaProfiloRoute
  '/verifica-identita/$id': typeof VerificaIdentitaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aggiorna-password': typeof AggiornaPasswordRoute
  '/come-funziona': typeof ComeFunzionaRoute
  '/conferma-email': typeof ConfermaEmailRoute
  '/contatti': typeof ContattiRoute
  '/cookie': typeof CookieRoute
  '/login': typeof LoginRoute
  '/messaggi': typeof MessaggiRoute
  '/prezzi': typeof PrezziRoute
  '/privacy': typeof PrivacyRoute
  '/recupera-password': typeof RecuperaPasswordRoute
  '/servizi': typeof ServiziRoute
  '/sicurezza': typeof SicurezzaRoute
  '/termini': typeof TerminiRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/famiglia/dashboard': typeof FamigliaDashboardRoute
  '/professionista/dashboard': typeof ProfessionistaDashboardRoute
  '/professionista/profilo': typeof ProfessionistaProfiloRoute
  '/verifica-identita/$id': typeof VerificaIdentitaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aggiorna-password'
    | '/come-funziona'
    | '/conferma-email'
    | '/contatti'
    | '/cookie'
    | '/login'
    | '/messaggi'
    | '/prezzi'
    | '/privacy'
    | '/recupera-password'
    | '/servizi'
    | '/sicurezza'
    | '/termini'
    | '/api/stripe-webhook'
    | '/chat/$conversationId'
    | '/famiglia/dashboard'
    | '/professionista/dashboard'
    | '/professionista/profilo'
    | '/verifica-identita/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/aggiorna-password'
    | '/come-funziona'
    | '/conferma-email'
    | '/contatti'
    | '/cookie'
    | '/login'
    | '/messaggi'
    | '/prezzi'
    | '/privacy'
    | '/recupera-password'
    | '/servizi'
    | '/sicurezza'
    | '/termini'
    | '/api/stripe-webhook'
    | '/chat/$conversationId'
    | '/famiglia/dashboard'
    | '/professionista/dashboard'
    | '/professionista/profilo'
    | '/verifica-identita/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aggiorna-password'
    | '/come-funziona'
    | '/conferma-email'
    | '/contatti'
    | '/cookie'
    | '/login'
    | '/messaggi'
    | '/prezzi'
    | '/privacy'
    | '/recupera-password'
    | '/servizi'
    | '/sicurezza'
    | '/termini'
    | '/api/stripe-webhook'
    | '/chat/$conversationId'
    | '/famiglia/dashboard'
    | '/professionista/dashboard'
    | '/professionista/profilo'
    | '/verifica-identita/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AggiornaPasswordRoute: typeof AggiornaPasswordRoute
  ComeFunzionaRoute: typeof ComeFunzionaRoute
  ConfermaEmailRoute: typeof ConfermaEmailRoute
  ContattiRoute: typeof ContattiRoute
  CookieRoute: typeof CookieRoute
  LoginRoute: typeof LoginRoute
  MessaggiRoute: typeof MessaggiRoute
  PrezziRoute: typeof PrezziRoute
  PrivacyRoute: typeof PrivacyRoute
  RecuperaPasswordRoute: typeof RecuperaPasswordRoute
  ServiziRoute: typeof ServiziRoute
  SicurezzaRoute: typeof SicurezzaRoute
  TerminiRoute: typeof TerminiRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ChatConversationIdRoute: typeof ChatConversationIdRoute
  FamigliaDashboardRoute: typeof FamigliaDashboardRoute
  ProfessionistaDashboardRoute: typeof ProfessionistaDashboardRoute
  ProfessionistaProfiloRoute: typeof ProfessionistaProfiloRoute
  VerificaIdentitaIdRoute: typeof VerificaIdentitaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termini': {
      id: '/termini'
      path: '/termini'
      fullPath: '/termini'
      preLoaderRoute: typeof TerminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sicurezza': {
      id: '/sicurezza'
      path: '/sicurezza'
      fullPath: '/sicurezza'
      preLoaderRoute: typeof SicurezzaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servizi': {
      id: '/servizi'
      path: '/servizi'
      fullPath: '/servizi'
      preLoaderRoute: typeof ServiziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recupera-password': {
      id: '/recupera-password'
      path: '/recupera-password'
      fullPath: '/recupera-password'
      preLoaderRoute: typeof RecuperaPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prezzi': {
      id: '/prezzi'
      path: '/prezzi'
      fullPath: '/prezzi'
      preLoaderRoute: typeof PrezziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messaggi': {
      id: '/messaggi'
      path: '/messaggi'
      fullPath: '/messaggi'
      preLoaderRoute: typeof MessaggiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie': {
      id: '/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferma-email': {
      id: '/conferma-email'
      path: '/conferma-email'
      fullPath: '/conferma-email'
      preLoaderRoute: typeof ConfermaEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/come-funziona': {
      id: '/come-funziona'
      path: '/come-funziona'
      fullPath: '/come-funziona'
      preLoaderRoute: typeof ComeFunzionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aggiorna-password': {
      id: '/aggiorna-password'
      path: '/aggiorna-password'
      fullPath: '/aggiorna-password'
      preLoaderRoute: typeof AggiornaPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifica-identita/$id': {
      id: '/verifica-identita/$id'
      path: '/verifica-identita/$id'
      fullPath: '/verifica-identita/$id'
      preLoaderRoute: typeof VerificaIdentitaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionista/profilo': {
      id: '/professionista/profilo'
      path: '/professionista/profilo'
      fullPath: '/professionista/profilo'
      preLoaderRoute: typeof ProfessionistaProfiloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionista/dashboard': {
      id: '/professionista/dashboard'
      path: '/professionista/dashboard'
      fullPath: '/professionista/dashboard'
      preLoaderRoute: typeof ProfessionistaDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/famiglia/dashboard': {
      id: '/famiglia/dashboard'
      path: '/famiglia/dashboard'
      fullPath: '/famiglia/dashboard'
      preLoaderRoute: typeof FamigliaDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$conversationId': {
      id: '/chat/$conversationId'
      path: '/chat/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof ChatConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AggiornaPasswordRoute: AggiornaPasswordRoute,
  ComeFunzionaRoute: ComeFunzionaRoute,
  ConfermaEmailRoute: ConfermaEmailRoute,
  ContattiRoute: ContattiRoute,
  CookieRoute: CookieRoute,
  LoginRoute: LoginRoute,
  MessaggiRoute: MessaggiRoute,
  PrezziRoute: PrezziRoute,
  PrivacyRoute: PrivacyRoute,
  RecuperaPasswordRoute: RecuperaPasswordRoute,
  ServiziRoute: ServiziRoute,
  SicurezzaRoute: SicurezzaRoute,
  TerminiRoute: TerminiRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ChatConversationIdRoute: ChatConversationIdRoute,
  FamigliaDashboardRoute: FamigliaDashboardRoute,
  ProfessionistaDashboardRoute: ProfessionistaDashboardRoute,
  ProfessionistaProfiloRoute: ProfessionistaProfiloRoute,
  VerificaIdentitaIdRoute: VerificaIdentitaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
